git clone https://github.com/QuantumRoboticsURC/bus_can_drive
git clone https://github.com/QuantumRoboticsURC/nmea_navsat_driver-melodic-devel
git clone https://github.com/QuantumRoboticsURC/qr_arm_lab
git clone https://github.com/QuantumRoboticsURC/ublox
git clone https://github.com/QuantumRoboticsURC/ros_imu_bno055
git clone https://github.com/QuantumRoboticsURC/usb_cam
git clone https://github.com/QuantumRoboticsURC/lost_comms_recovery
git clone https://github.com/QuantumRoboticsURC/simple_drive
git clone https://github.com/QuantumRoboticsURC/nav_dif
